version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  admin-ui:
    build: ./admin-ui
    ports:
      - "8081:80"
  dataset-api:
    build: ./dataset-api
    ports:
      - "8082:80"
    volumes:
      - ./dataset-api/dataset.db:/app/dataset.db
      - data_volume:/app/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  training-api:
    build: ./training-api
    ports:
      - "8083:80"
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_URL=redis://redis:6379
      - DATASET_API_URL=http://dataset-api:80
      - TRAINING_API_URL=http://training-api:80
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    volumes:
      - ./training-api/training.db:/app/training.db
  training-worker:
    build: ./training-worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - TRAINING_API_URL=http://training-api:80
    volumes:
      - data_volume:/app/data
      - model_volume:/app/model
  data-producer:
    build: ./data-producer
    depends_on:
      - kafka
  inference-consumer:
    build: ./inference-consumer
    depends_on:
      - kafka
    environment:
      - INFERENCE_API_URL=http://inference-api:80
    volumes:
      - ./inference-consumer/inference.db:/app/inference.db
      - model_volume:/app/model
  inference-api:
    build: ./inference-api
    ports:
      - "8084:80"
    volumes:
      - ./inference-api/inference.db:/app/inference.db
volumes:
  data_volume:
  model_volume:
