version: '3.8'
services:
  dataset-api:
    build: ./dataset-api
    ports:
      - "8081:80"
    volumes:
      - data_volume:/app/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  training-api:
    build: ./training-api
    ports:
      - "8082:80"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATASET_API_URL=http://dataset-api:80
  training-worker:
    build: ./training-worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - TRAINING_API_URL=http://training-api:80
    volumes:
      - data_volume:/app/data
volumes:
  data_volume:
  model_volume:
